-- AlterTable GuildSettings
ALTER TABLE "GuildSettings" ADD COLUMN IF NOT EXISTS "hgDefaultWinPrize" INTEGER NOT NULL DEFAULT 250;
ALTER TABLE "GuildSettings" ADD COLUMN IF NOT EXISTS "hgDefaultReviveCost" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "GuildSettings" ADD COLUMN IF NOT EXISTS "hgDefaultMaxRevives" INTEGER NOT NULL DEFAULT 2;

-- AlterTable ArenaGame
ALTER TABLE "ArenaGame" ADD COLUMN IF NOT EXISTS "winPrize" INTEGER NOT NULL DEFAULT 250;
ALTER TABLE "ArenaGame" ADD COLUMN IF NOT EXISTS "reviveCost" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "ArenaGame" ADD COLUMN IF NOT EXISTS "maxRevives" INTEGER NOT NULL DEFAULT 2;

-- AlterTable ArenaTribute
ALTER TABLE "ArenaTribute" ADD COLUMN IF NOT EXISTS "revivesUsed" INTEGER NOT NULL DEFAULT 0;
